Counselorinfosection/urls.py
from django.urls import path
from . import views

app_name = "infosection"

urlpatterns = [
    path('',views.info,name="info"),
    path('infoadd/',views.infoadd,name="infoadd"),
    path("infoaddrec/",views.infoaddrec,name="infoaddrec"),
    path('infodelete/<int:id>/',views.infodelete,name="infodelete"),
    path('infoupdate/<int:id>/',views.infoupdate,name="infoupdate"),
    path('infoupdate/uprec/<int:id>/',views.infouprec,name="infouprec"),
]

Home/urls.py
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('', views.HomeView, name='home'),
    path("signup/", views.RegistrationView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView, name='logout'),
]

miniITproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('UserExercise.urls')),
    path('', include('UserTestimonial.urls')),
    path('', include('UserRead.urls')),
    path('student/', include('StudentHomePage.urls')),
    path('student/', include('StudentProfile.urls')),
    path('student/', include('StudentAppointment.urls')),
    path('student/', include('StudentQuiz.urls')),
    path('student/', include('StudentDiary.urls')),
    path('counselor/', include('CounselorQuiz.urls')),
    path('counselor/', include('CounselorProfile.urls')),
    path('counselor/', include('Counselorinfosection.urls')),
    path('counselor/', include('CounselorSchedule.urls')),
    path('counselor/', include('CounselorAppointment.urls')),
    path('counselor/', include('CounselorProgressReport.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "The Empathy Oasis"
admin.site.site_title = "The Empathy Oasis Admin Portal"
admin.site.index_title = "Welcome to Admin Portal"

Counselorinfosection/models.py
from django.db import models
from django.utils import timezone
from Home.models import Counselor

# Create your models here.
class Info(models.Model):
    counselor = models.ForeignKey(Counselor, on_delete=models.CASCADE, related_name='infos')
    title = models.CharField(max_length=100)
    info = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title  #return title of info section as a string
    
    class Meta:
        verbose_name_plural = "Infos"  #set the plural name of the model

Counselorinfosection/views.py
from django.shortcuts import redirect, render
from .models import Info
from django.contrib.auth.decorators import login_required
from Home.decorators import counselor_required

# Create your views here.

@counselor_required
def info(request):

    """Displays information posted by the logged in counselor."""

    info=Info.objects.all() 
    return render(request,'counselorinfosection.html',{'info':info})

@counselor_required
def infoadd(request):
    return render(request,'counseloraddinfo.html')

@counselor_required
def infoaddrec(request): #add info
    if request.method == 'POST':
      v=request.POST['title']
      w=request.POST['info']
      x=request.user.counselor
      info=Info(counselor=x,title=v,info=w)
      info.save()
      return redirect('infosection:info')

@counselor_required #delete info
def infodelete(request,id):
    info=Info.objects.get(id=id)
    info.delete()
    return redirect('infosection:info')

@counselor_required #get the id of the info to update
def infoupdate(request,id):
    info=Info.objects.get(id=id)
    return render(request,'counselorupdateinfo.html',{'info':info})

@counselor_required #update info
def infouprec(request,id):       
    v=request.POST['title']
    w=request.POST['info']
    info=Info.objects.get(id=id)
    info.title=v
    info.info=w
    info.save()
    return redirect('infosection:info')

Counselorinfosection/templates/counseloraddinfo.html
{% extends 'counselornav.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'counselorschedulestyle.css' %}">

<body>
    <!-- styling title -->
    <div class="moving_title">
        <span>A</span>
        <span>D</span>
        <span>D</span>
        <span></span>
        <span>A</span>
        <span>N</span>
        <span></span>
        <span>I</span>
        <span>N</span>
        <span>F</span>
        <span>O</span>
    </div>
    <br><br>
    <div class="container1">
        <!-- form to add info -->
        <form action="{% url 'infosection:infoaddrec' %}" method="post">
            {% csrf_token %}
            <label for="">Title</label><br><br>
            <input type="text" name="title" required><br><br> 
            <label for="">Info</label><br><br>
            <textarea name="info" id="info" rows="15" cols="70" required></textarea><br><br> 
            <button type="submit" id="new">Submit</button>
        </form>
    </div>
</body>
</html>
{% endblock content %}

Counselorinfosection/templates/counselorinfosection.html
{% extends 'counselornav.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Info Section</title>
</head>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'counselorinfosectionstyle.css' %}">
<body>
  <div class="main">
    <!-- displaying the info section and counselor is able to edit or delete -->
    <div class="intro">
      <h1>Mental Wellness: Taking Care of Your Mental Health</h1><br><br>
      <p><i>Empowering Minds, Embracing Wellness: Your Journey to Mental Well-Being Begins Here</i></p>
    </div>
    <br>
    <div class="infos">
      <table>
        <div class="content">
          {% for x in info %}
          <tr>
            <td>
              <div class="t1">
                <div class="zoom">
                  <div id="info_title">{{x.title}}</div>
                </div>
              </div>
            </td>
            <div class="desc">
              <td class="t2">
                {{x.info}}
              </td>
            </div>
            <td>
              <a href="infoupdate/{{x.id}}"><button id="up"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a>
            </td>
            <td>
              <a href="infodelete/{{x.id}}"><button id="del"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a>
            </td>
          </tr>
          {% endfor %}
        </div>
      </table>
      <br><br><br>
      <a href="{% url 'infosection:infoadd' %}"><button id="new3">Add an info</button></a>
    </div>
  </div>
  <br><br>
</body>
</html>
{% endblock content %}

Counselorinfosection/templates/counselorupdateinfo.html
{% extends 'counselornav.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'counselorschedulestyle.css' %}">

<body>
    <!-- styling title -->
    <div class="moving_title">
        <span>U</span>
        <span>P</span>
        <span>D</span>
        <span>A</span>
        <span>T</span>
        <span>E</span>
        <span></span>
        <span>I</span>
        <span>N</span>
        <span>F</span>
        <span>O</span>
    </div>
    <br><br>
    <div class="container1">
        <!-- form to update info section -->
        <form action="{% url 'infosection:infouprec' info.id %}" method="post">
            {% csrf_token %}
            <label for="">Title</label><br><br>
            <input type="text" name="title" value="{{info.title}}"><br><br>
            <label for="">Info</label><br><br>
            <textarea name="info" rows="15" cols="70">{{ info.info|default_if_none:'' }}</textarea><br><br>
            <button type="submit" id="new">Update</button>
        </form>

    </div>
</body>

</html>
{% endblock content %}