Home/urls.py
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('', views.HomeView, name='home'),
    path("signup/", views.RegistrationView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView, name='logout'),
]

StudentDiary/urls.py
from django.urls import path
from . import views

app_name = "StudentDiary"

urlpatterns = [
    path('diary',views.diary,name="diary"),
    path('diaryadd/',views.diaryadd,name="diaryadd"),
    path("diaryaddrec/",views.diaryaddrec,name="diaryaddrec"),
    path('diarydelete/<int:id>/',views.diarydelete,name="diarydelete"),
    path('diaryupdate/<int:id>/',views.diaryupdate,name="diaryupdate"),
    path('diaryupdate/uprec/<int:id>/',views.diaryuprec,name="diaryuprec"),
]

StudentHomePage/urls.py
from django.urls import path
from . import views

app_name = "StudentHomePage"

urlpatterns = [
    path('', views.IndexView, name="index"),
]

StudentProfile/urls.py
from django.urls import path
from . import views

app_name = "StudentProfile"

urlpatterns = [
    path('profile/', views.ProfileView, name="studentprofile"),
    path('editprofile/', views.EditProfileView, name="studentedit"),
    path('changepassword/', views.StudentChangePasswordView.as_view(), name='studentchangepassword'),
]

 

StudentQuiz/urls.py
from django.urls import path
from . import views

app_name = "StudentQuiz"

urlpatterns = [
    path('quiz/',views.QuestionView,name="quiz"),
    path('quiz/result/', views.ScoreView,name="result"),
]

miniITproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('UserExercise.urls')),
    path('', include('UserTestimonial.urls')),
    path('', include('UserRead.urls')),
    path('student/', include('StudentHomePage.urls')),
    path('student/', include('StudentProfile.urls')),
    path('student/', include('StudentAppointment.urls')),
    path('student/', include('StudentQuiz.urls')),
    path('student/', include('StudentDiary.urls')),
    path('counselor/', include('CounselorQuiz.urls')),
    path('counselor/', include('CounselorProfile.urls')),
    path('counselor/', include('Counselorinfosection.urls')),
    path('counselor/', include('CounselorSchedule.urls')),
    path('counselor/', include('CounselorAppointment.urls')),
    path('counselor/', include('CounselorProgressReport.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "The Empathy Oasis"
admin.site.site_title = "The Empathy Oasis Admin Portal"
admin.site.index_title = "Welcome to Admin Portal"

StudentNavBar/models.py
from django.db import models

# Create your models here.

StudentNavBar/views.py
from django.shortcuts import render

# Create your views here.

StudentNavBar/templates/studentnavbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head> 
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--style for StudentHome.html-->
        <link rel="stylesheet" href="{% static 'studentnavbarstyle.css' %}">
        <!--Icons-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
        <div class="main_body">
            <!--sidebar-->
            <aside>
                <img src="{% static 'images/logo.png' %}" class="logo">
                <div class="option">
                    <a href="{% url 'StudentHomePage:index' %}" class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a>
                    <a href="{% url 'StudentProfile:studentprofile' %}" class="{% if request.resolver_match.url_name == 'studentprofile' or request.resolver_match.url_name == 'studentedit' or request.resolver_match.url_name == 'studentchangepassword'%}active{% endif %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i>My profile</a>
                    <a href="{% url 'StudentDiary:diary' %}" class="{% if request.resolver_match.url_name == 'diary' %}active{% endif %}"><i class="fa fa-book" aria-hidden="true"></i>Diary</a>
                    <a href="{% url 'StudentAppointment:myAppointment' %}" class="{% if request.resolver_match.url_name == 'myAppointment'%}active{% endif %}"><i class="fa fa-calendar-o" aria-hidden="true"></i>Appointment</a>
                    <a href="{% url 'StudentAppointment:experts' %}" class="{% if request.resolver_match.url_name == 'experts' or request.resolver_match.url_name == 'appointment'%}active{% endif %}"><i class="fa fa-group" aria-hidden="true"></i>Experts</a>
                    <a href="{% url 'StudentQuiz:quiz' %}" class="{% if request.resolver_match.url_name == 'quiz' or request.resolver_match.url_name == 'result' %}active{% endif %}"><i class="fa fa-edit" aria-hidden="true"></i>Assessment</a>
                    <a href="{% url 'Home:logout' %}" class="{% if request.resolver_match.url_name == 'logout'}"><i class="fa fa-sign-out" aria-hidden="true"></i>Log Out</a>
                </div>
            </aside>
            <!--sidebar end-->

            <div class="content">
                {% block content %} {% endblock content %}
            </div>
        </div>
    </body>

</html>