Home/urls.py
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('', views.HomeView, name='home'),
    path("signup/", views.RegistrationView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView, name='logout'),
]

UserExercise/urls.py
from django.urls import path
from . import views

app_name = "UserExercise"

urlpatterns = [
    path('exercise/',views.exercises_page,name="exercise"),
]

UserRead/urls.py
from django.urls import path
from . import views

app_name = "UserRead"

urlpatterns = [
    path('read/',views.ReadView, name="read"),
    path('read/1', views.Book1View, name="book1"),
    path('read/2', views.Book2View, name="book2"),
    path('read/3', views.Book3View, name="book3"),
    path('read/4', views.Book4View, name="book4"),
    path('read/5', views.Book5View, name="book5"),
]

UserTestimonial/urls.py
from django.urls import path
from . import views

app_name = "UserTestimonial"

urlpatterns = [
    path('testimonial/',views.TestimonialView, name="testimonial"),
]

miniITproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('UserExercise.urls')),
    path('', include('UserTestimonial.urls')),
    path('', include('UserRead.urls')),
    path('student/', include('StudentHomePage.urls')),
    path('student/', include('StudentProfile.urls')),
    path('student/', include('StudentAppointment.urls')),
    path('student/', include('StudentQuiz.urls')),
    path('student/', include('StudentDiary.urls')),
    path('counselor/', include('CounselorQuiz.urls')),
    path('counselor/', include('CounselorProfile.urls')),
    path('counselor/', include('Counselorinfosection.urls')),
    path('counselor/', include('CounselorSchedule.urls')),
    path('counselor/', include('CounselorAppointment.urls')),
    path('counselor/', include('CounselorProgressReport.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "The Empathy Oasis"
admin.site.site_title = "The Empathy Oasis Admin Portal"
admin.site.index_title = "Welcome to Admin Portal"

UserRead/models.py
from django.db import models

# Create your models here.

UserRead/views.py
from django.shortcuts import render

# Create your views here.
def ReadView(request):
    return render(request, 'read.html')

def Book1View(request):
    return render(request, 'book1.html')

def Book2View(request):
    return render(request, 'book2.html')

def Book3View(request):
    return render(request, 'book3.html')

def Book4View(request):
    return render(request, 'book4.html')

def Book5View(request):
    return render(request, 'book5.html')

UserRead/templates/book1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bookstyle.css' %}">
        <!--Icons-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Read</title>
    </head>
    <body>
        <div class="bookPage">
            <header class="navbar">
                <img src="{% static 'images/logo.png' %}" class="logo">
                <nav class="navigation">
                    <a href="{% url 'Home:home' %}">Home</a>
                    <a href="{% url 'UserTestimonial:testimonial' %}">Inspire</a>
                    <a href="{% url 'UserExercise:exercise' %}">Nurture</a>
                    <a href="{% url 'UserRead:read' %}" class="active">Explore</a>
                    <a href="{% url 'Home:login' %}">Log In</a>
                </nav>
            </header>
            <div class="header">
                <div class="head">
                  <div class="desc">
                    <p>Mood Crew Workbook</p>
                  </div>
                  <div class="audio">
                    <p><i>Want some music? >></i></p>
                    <audio id="nyan" src="{% static 'song1.mp3' %}" preload="metadata" type="audio/mpeg">
                        Your browser does not support the audio element.
                     </audio>
                     <a class="btn" id="nyan-btn"><span></span></a>
                  </div>
                </div>
                <div class="bookCon">
                  <iframe class="book" src="http://flowpaper.com/flipbook/https://www.dbsalliance.org/wp-content/uploads/2022/10/MoodCrew_Workbook.pdf" width="100%" height="600" allowFullScreen>
                  </iframe>
                </div>
            </div>
        <!--<iframe src="https://online.anyflip.com/ejfkz/zofc/mobile/index.html" width="70%" height="500" style="border: none;" allowFullScreen>
        </iframe>-->
        <!--<embed src="https://dekkocomics.com/mental-health-wellbeing-free" width="500" height="200">-->
        </div>
        <script>
            var nyan = document.getElementById('nyan');
var nyanBtn = document.getElementById('nyan-btn');

function playPause(song){
   if (song.paused && song.currentTime >= 0 && !song.ended) {
      song.play();
   } else {
      song.pause();
   }
}

function reset(btn, song){
   if(btn.classList.contains('playing')){
      btn.classList.toggle('playing');
   }
   song.pause();
   song.currentTime = 0;
}

function progress(btn, song){
   setTimeout(function(){
      var end = song.duration; 
      var current = song.currentTime;
      var percent = current/(end/100);
      //check if song is at the end
      if(current==end){
         reset(btn, song);
      }
      //set inset box shadow
      btn.style.boxShadow = "inset " + btn.offsetWidth * (percent/100) + "px 0px 0px 0px rgba(0,0,0,0.125)"
      //call function again
      progress(btn, song);     
   }, 1000);
}

nyanBtn.addEventListener('click', function(){
   nyanBtn.classList.toggle('playing');
   playPause(nyan);
   progress(nyanBtn, nyan);
});


        </script>
    </body>
</html>

UserRead/templates/book2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bookstyle.css' %}">
        <!--Icons-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Read</title>
    </head>
    <body>
        <div class="bookPage">
            <header class="navbar">
               <img src="{% static 'images/logo.png' %}" class="logo">
               <nav class="navigation">
                  <a href="{% url 'Home:home' %}">Home</a>
                  <a href="{% url 'UserTestimonial:testimonial' %}">Inspire</a>
                  <a href="{% url 'UserExercise:exercise' %}">Nurture</a>
                  <a href="{% url 'UserRead:read' %}" class="active">Explore</a>
                  <a href="{% url 'Home:login' %}">Log In</a>
               </nav>
            </header>
            <div class="header">
                <div class="head">
                  <div class="desc">
                    <p>Walk with Gandhi</p>
                  </div>
                  <div class="audio">
                    <p><i>Want some music? >></i></p>
                    <audio id="nyan" src="{% static 'song1.mp3' %}" preload="metadata" type="audio/mpeg">
                        Your browser does not support the audio element.
                     </audio>
                     <a class="btn" id="nyan-btn"><span></span></a>
                  </div>
                </div>
                <div class="bookCon">
                    <iframe class="book" src="http://flowpaper.com/flipbook/https://freekidsbooks.org/wp-content/uploads/2022/12/Walk_with_Gandhi-GR-FKB.pdf" width="100%" height="600" allowFullScreen>
                    </iframe>
                </div>
            </div>
        <!--<iframe src="https://online.anyflip.com/ejfkz/zofc/mobile/index.html" width="70%" height="500" style="border: none;" allowFullScreen>
        </iframe>-->
        <!--<embed src="https://dekkocomics.com/mental-health-wellbeing-free" width="500" height="200">-->
        </div>
        <script>
            var nyan = document.getElementById('nyan');
var nyanBtn = document.getElementById('nyan-btn');

function playPause(song){
   if (song.paused && song.currentTime >= 0 && !song.ended) {
      song.play();
   } else {
      song.pause();
   }
}

function reset(btn, song){
   if(btn.classList.contains('playing')){
      btn.classList.toggle('playing');
   }
   song.pause();
   song.currentTime = 0;
}

function progress(btn, song){
   setTimeout(function(){
      var end = song.duration; 
      var current = song.currentTime;
      var percent = current/(end/100);
      //check if song is at the end
      if(current==end){
         reset(btn, song);
      }
      //set inset box shadow
      btn.style.boxShadow = "inset " + btn.offsetWidth * (percent/100) + "px 0px 0px 0px rgba(0,0,0,0.125)"
      //call function again
      progress(btn, song);     
   }, 1000);
}

nyanBtn.addEventListener('click', function(){
   nyanBtn.classList.toggle('playing');
   playPause(nyan);
   progress(nyanBtn, nyan);
});


        </script>
    </body>
</html>

UserRead/templates/book3.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bookstyle.css' %}">
        <!--Icons-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Read</title>
    </head>
    <body>
        <div class="bookPage">
            <header class="navbar">
               <img src="{% static 'images/logo.png' %}" class="logo">
               <nav class="navigation">
                  <a href="{% url 'Home:home' %}">Home</a>
                  <a href="{% url 'UserTestimonial:testimonial' %}">Inspire</a>
                  <a href="{% url 'UserExercise:exercise' %}">Nurture</a>
                  <a href="{% url 'UserRead:read' %}" class="active">Explore</a>
                  <a href="{% url 'Home:login' %}">Log In</a>
               </nav>
            </header>
            <div class="header">
                <div class="head">
                  <div class="desc">
                    <p>Dekko Comics - Mental Heath & Wellbeing</p>
                  </div>
                  <div class="audio">
                    <p><i>Want some music? >></i></p>
                    <audio id="nyan" src="{% static 'song1.mp3' %}" preload="metadata" type="audio/mpeg">
                        Your browser does not support the audio element.
                     </audio>
                     <a class="btn" id="nyan-btn"><span></span></a>
                  </div>
                </div>
                <div class="bookCon">
                    <embed src="https://dekkocomics.com/mental-health-wellbeing-free" width="100%" height="600">
                </div>
            </div>
        <!--<iframe src="https://online.anyflip.com/ejfkz/zofc/mobile/index.html" width="70%" height="500" style="border: none;" allowFullScreen>
        </iframe>-->
        <!---->
        </div>
        <script>
            var nyan = document.getElementById('nyan');
var nyanBtn = document.getElementById('nyan-btn');

function playPause(song){
   if (song.paused && song.currentTime >= 0 && !song.ended) {
      song.play();
   } else {
      song.pause();
   }
}

function reset(btn, song){
   if(btn.classList.contains('playing')){
      btn.classList.toggle('playing');
   }
   song.pause();
   song.currentTime = 0;
}

function progress(btn, song){
   setTimeout(function(){
      var end = song.duration; 
      var current = song.currentTime;
      var percent = current/(end/100);
      //check if song is at the end
      if(current==end){
         reset(btn, song);
      }
      //set inset box shadow
      btn.style.boxShadow = "inset " + btn.offsetWidth * (percent/100) + "px 0px 0px 0px rgba(0,0,0,0.125)"
      //call function again
      progress(btn, song);     
   }, 1000);
}

nyanBtn.addEventListener('click', function(){
   nyanBtn.classList.toggle('playing');
   playPause(nyan);
   progress(nyanBtn, nyan);
});


        </script>
    </body>
</html>

UserRead/templates/book4.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bookstyle.css' %}">
        <!--Icons-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Read</title>
    </head>
    <body>
        <div class="bookPage">
            <header class="navbar">
               <img src="{% static 'images/logo.png' %}" class="logo">
               <nav class="navigation">
                  <a href="{% url 'Home:home' %}">Home</a>
                  <a href="{% url 'UserTestimonial:testimonial' %}">Inspire</a>
                  <a href="{% url 'UserExercise:exercise' %}">Nurture</a>
                  <a href="{% url 'UserRead:read' %}" class="active">Explore</a>
                  <a href="{% url 'Home:login' %}">Log In</a>
               </nav>
            </header>
            <div class="header">
                <div class="head">
                  <div class="desc">
                    <p>Living Bipolar</p>
                  </div>
                  <div class="audio">
                    <p><i>Want some music? >></i></p>
                    <audio id="nyan" src="{% static 'song1.mp3' %}" preload="metadata" type="audio/mpeg">
                        Your browser does not support the audio element.
                     </audio>
                     <a class="btn" id="nyan-btn"><span></span></a>
                  </div>
                </div>
                <div class="bookCon">
                    <iframe src="https://online.anyflip.com/ejfkz/zofc/mobile/index.html" width="70%" height="500" style="border: none;" allowFullScreen>
                    </iframe>
                </div>
            </div>
       
        </div>
        <script>
            var nyan = document.getElementById('nyan');
var nyanBtn = document.getElementById('nyan-btn');

function playPause(song){
   if (song.paused && song.currentTime >= 0 && !song.ended) {
      song.play();
   } else {
      song.pause();
   }
}

function reset(btn, song){
   if(btn.classList.contains('playing')){
      btn.classList.toggle('playing');
   }
   song.pause();
   song.currentTime = 0;
}

function progress(btn, song){
   setTimeout(function(){
      var end = song.duration; 
      var current = song.currentTime;
      var percent = current/(end/100);
      //check if song is at the end
      if(current==end){
         reset(btn, song);
      }
      //set inset box shadow
      btn.style.boxShadow = "inset " + btn.offsetWidth * (percent/100) + "px 0px 0px 0px rgba(0,0,0,0.125)"
      //call function again
      progress(btn, song);     
   }, 1000);
}

nyanBtn.addEventListener('click', function(){
   nyanBtn.classList.toggle('playing');
   playPause(nyan);
   progress(nyanBtn, nyan);
});


        </script>
    </body>
</html>

UserRead/templates/book5.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bookstyle.css' %}">
        <!--Icons-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Read</title>
    </head>
    <body>
        <div class="bookPage">
            <header class="navbar">
               <img src="{% static 'images/logo.png' %}" class="logo">
               <nav class="navigation">
                  <a href="{% url 'Home:home' %}">Home</a>
                  <a href="{% url 'UserTestimonial:testimonial' %}">Inspire</a>
                  <a href="{% url 'UserExercise:exercise' %}">Nurture</a>
                  <a href="{% url 'UserRead:read' %}" class="active">Explore</a>
                  <a href="{% url 'Home:login' %}">Log In</a>
               </nav>
            </header>
            <div class="header">
                <div class="head">
                  <div class="desc">
                    <p>Counselling for Toads: A psychological Adventure </p>
                  </div>
                  <div class="audio">
                    <p><i>Want some music? >></i></p>
                    <audio id="nyan" src="{% static 'song1.mp3' %}" preload="metadata" type="audio/mpeg">
                        Your browser does not support the audio element.
                     </audio>
                     <a class="btn" id="nyan-btn"><span></span></a>
                  </div>
                </div>
                <div class="bookCon">
                    <iframe src="https://online.anyflip.com/ejfkz/oxuy/mobile/index.html" width="70%" height="500" style="border: none;" allowFullScreen>
                    </iframe>
                </div>
            </div>
       
        </div>
        <script>
            var nyan = document.getElementById('nyan');
var nyanBtn = document.getElementById('nyan-btn');

function playPause(song){
   if (song.paused && song.currentTime >= 0 && !song.ended) {
      song.play();
   } else {
      song.pause();
   }
}

function reset(btn, song){
   if(btn.classList.contains('playing')){
      btn.classList.toggle('playing');
   }
   song.pause();
   song.currentTime = 0;
}

function progress(btn, song){
   setTimeout(function(){
      var end = song.duration; 
      var current = song.currentTime;
      var percent = current/(end/100);
      //check if song is at the end
      if(current==end){
         reset(btn, song);
      }
      //set inset box shadow
      btn.style.boxShadow = "inset " + btn.offsetWidth * (percent/100) + "px 0px 0px 0px rgba(0,0,0,0.125)"
      //call function again
      progress(btn, song);     
   }, 1000);
}

nyanBtn.addEventListener('click', function(){
   nyanBtn.classList.toggle('playing');
   playPause(nyan);
   progress(nyanBtn, nyan);
});


        </script>
    </body>
</html>

UserRead/templates/read.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'readstyle.css' %}">
        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
        <!--Icons-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Read</title>
    </head>
    <body>

        <div class="ReadPage">
            <header class="navbar">
                <img src="{% static 'images/logo.png' %}" class="logo">
                <nav class="navigation">
                    <a href="{% url 'Home:home' %}">Home</a>
                    <a href="{% url 'UserTestimonial:testimonial' %}">Inspire</a>
                    <a href="{% url 'UserExercise:exercise' %}">Nurture</a>
                    <a href="{% url 'UserRead:read' %}" class="active">Explore</a>
                    <a href="{% url 'Home:login' %}">Log In</a>
                </nav>
            </header>
            <div class="header">
                <div class="titletop">
                  <p class="title">Find your</p>
                  <p class="title">Best Friend.</p>
                  <p class="desc">Any pages turned today?</p>
                </div>

                <div class="scene">
                    <div class="book-wrap">
                      <div class="left-side">
                        <div class="book-cover-left"></div>
                        <div class="layer1">
                          <div class="page-left"></div>
                        </div>
                        <div class="layer2">
                          <div class="page-left"></div>
                        </div>
                        <div class="layer3">
                          <div class="page-left"></div>
                        </div>
                        <div class="layer4">
                          <div class="page-left"></div>
                        </div>
                        <div class="layer-text">
                          <div class="page-left-2">
                            <div class="corner"></div>
                            <div class="corner2"></div>
                            <div class="corner-fold"></div>
                            <div class="page-text w-richtext">
                              <h3><strong>Do you know?</strong></h3>
                              <p>‍</p>
                              <p>Reading actually help your mental health!</p><br>
                              <p>It's like having a never-ending sleepover with your funniest friends. You can have a tea party with the Mad Hatter, solve mysteries with Sherlock Holmes, and go on epic quests with brave knights – all without leaving your cozy reading nook!</p>
                              <p></p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="center"></div>
                      <div class="right-side">
                        <div class="book-cover-right"></div>
                        <div class="layer1">
                          <div class="page-right"></div>
                        </div>
                        <div class="layer2 right">
                          <div class="page-right"></div>
                        </div>
                        <div class="layer3 right">
                          <div class="page-right"></div>
                        </div>
                        <div class="layer4 right">
                          <div class="page-right"></div>
                        </div>
                        <div class="layer-text right">
                          <div class="page-right-2">
                            <div class="page-text w-richtext">
                              <br>
                              <p>‍</p>
                              <p><p>So, why not grab a book, snuggle up with a fuzzy blanket, and let your mind dance in the rainbows of storytelling magic?</p></p><br><br>
                              <p>Let's dive into the sea of books!</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
            
            <section class="div2">
            <div class="featured" id="featured">
                <h1 class="heading"><span>Featured books</span></h1>
                <div class="swiper featured-slider">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide box">
                          <div class="bookcontainer">
                            <div class="book">
                              <div class="inner-book">
                                <div class="img" style="padding-top: calc(1.07 * 100%)">
                                  <img src="{% static 'images/mood.png' %}" />
                                </div>
                                <div class="page"></div>
                                <div class="page page-2"></div>
                                <div class="page page-3"></div>
                                <div class="page page-4"></div>
                                <div class="page page-5"></div>
                                
                              </div>
                            </div>
                          </div>
                          <div class="content">
                            <h3>Mood Crew®</h3>
                            <a href="{% url 'UserRead:book1' %}" class="btn">Read</a>
                          </div>
                        </div>

                        <div class="swiper-slide box">
                            <div class="bookcontainer">
                              <div class="book">
                                <div class="inner-book">
                                  <div class="img" style="padding-top: calc(1.07 * 100%)">
                                    <img src="{% static 'images/gandhi.jpg' %}" />
                                  </div>
                                  <div class="page"></div>
                                  <div class="page page-2"></div>
                                  <div class="page page-3"></div>
                                  <div class="page page-4"></div>
                                  <div class="page page-5"></div>
                                  
                                </div>
                              </div>
                            </div>
                            <div class="content">
                              <h3>Walk with Gandhi</h3>
                              <a href="{% url 'UserRead:book2' %}" class="btn">Read</a>
                            </div>
                          </div>

                          <div class="swiper-slide box">
                            <div class="bookcontainer">
                              <div class="book">
                                <div class="inner-book">
                                  <div class="img" style="padding-top: calc(1.07 * 100%)">
                                    <img src="{% static 'images/blue.jpg' %}" />
                                  </div>
                                  <div class="page"></div>
                                  <div class="page page-2"></div>
                                  <div class="page page-3"></div>
                                  <div class="page page-4"></div>
                                  <div class="page page-5"></div>
                                  
                                </div>
                              </div>
                            </div>
                            <div class="content">
                              <h3>Dekko Comics</h3>
                              <a href="{% url 'UserRead:book3' %}" class="btn">Read</a>
                            </div>
                          </div>

                          <div class="swiper-slide box">
                            <div class="bookcontainer">
                              <div class="book">
                                <div class="inner-book">
                                  <div class="img" style="padding-top: calc(1.07 * 100%)">
                                    <img src="{% static 'images/bipolar.png' %}" />
                                  </div>
                                  <div class="page"></div>
                                  <div class="page page-2"></div>
                                  <div class="page page-3"></div>
                                  <div class="page page-4"></div>
                                  <div class="page page-5"></div>
                                  
                                </div>
                              </div>
                            </div>
                            <div class="content">
                              <h3>Living Bipolar</h3>
                              <a href="{% url 'UserRead:book4' %}" class="btn">Read</a>
                            </div>
                          </div>

                          <div class="swiper-slide box">
                            <div class="bookcontainer">
                              <div class="book">
                                <div class="inner-book">
                                  <div class="img" style="padding-top: calc(1.07 * 100%)">
                                    <img src="{% static 'images/toad.png' %}" />
                                  </div>
                                  <div class="page"></div>
                                  <div class="page page-2"></div>
                                  <div class="page page-3"></div>
                                  <div class="page page-4"></div>
                                  <div class="page page-5"></div>
                                  
                                </div>
                              </div>
                            </div>
                            <div class="content">
                              <h3>Counselling for Toads: A psychological Adventure [Mandarin]</h3>
                              <a href="{% url 'UserRead:book5' %}" class="btn">Read</a>
                            </div>
                          </div>
                    </div>
                    <div class="swiper-button-next"></div>
                    <div class="swiper-button-prev"></div>
                </div>
            </div>
        </section>
        </div>

        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
        <script>
                                              
const swiper = new Swiper(".featured-slider", {
    spaceBetween: 30,
    loop:true,
    centeredSlides:true, 
    autoplay: {
        delay: 6500,
        disableOnInteraction: false,
    },
    navigation:{
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
    },
    breakpoints: {
        0: {
            slidesPerView: 1,
        },
        450: {
            slidesPerView: 2,
        },
        768: {
            slidesPerView: 3,
        },
        1024: {
            slidesPerView: 4,
        },
    },
});

window.onscroll = () => {
          const nav = document.querySelector('.navbar');
          if(this.scrollY <= 230) nav.className = 'navbar'; else nav.className = 'navbar scroll';
        };

        </script>
    </body>
</html>