CounselorQuiz/urls.py
from django.urls import path
from . import views

app_name = "CounselorQuiz"

urlpatterns = [
    path('questions/', views.quiz_question_list, name='quiz_question_list'),
    path('questions/create/', views.quiz_question_create, name='quiz_question_create'),
    path('questions/update/<int:question_id>/', views.quiz_question_update, name='quiz_question_update'),
    path('questions/delete/<int:question_id>/', views.quiz_question_delete, name='quiz_question_delete'),
]

Home/urls.py
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('', views.HomeView, name='home'),
    path("signup/", views.RegistrationView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView, name='logout'),
]

miniITproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('UserExercise.urls')),
    path('', include('UserTestimonial.urls')),
    path('', include('UserRead.urls')),
    path('student/', include('StudentHomePage.urls')),
    path('student/', include('StudentProfile.urls')),
    path('student/', include('StudentAppointment.urls')),
    path('student/', include('StudentQuiz.urls')),
    path('student/', include('StudentDiary.urls')),
    path('counselor/', include('CounselorQuiz.urls')),
    path('counselor/', include('CounselorProfile.urls')),
    path('counselor/', include('Counselorinfosection.urls')),
    path('counselor/', include('CounselorSchedule.urls')),
    path('counselor/', include('CounselorAppointment.urls')),
    path('counselor/', include('CounselorProgressReport.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "The Empathy Oasis"
admin.site.site_title = "The Empathy Oasis Admin Portal"
admin.site.index_title = "Welcome to Admin Portal"

CounselorQuiz/models.py
from django.db import models
from Home.models import Counselor

# Create your models here.
class QuizQuestion(models.Model):
    counselor = models.ForeignKey(Counselor, on_delete=models.CASCADE, related_name='questions')
    question_text = models.CharField(max_length=200)

    def __str__(self): 
        return self.question_text
    
    class Meta:
        verbose_name_plural = "Quiz Questions"

class QuizOption(models.Model):
    question = models.ForeignKey(QuizQuestion, on_delete=models.CASCADE)
    option_text = models.CharField(max_length=200)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.option_text
    
    class Meta:
        verbose_name_plural = "Quiz Options"
    

CounselorQuiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import QuizQuestion, QuizOption
from Home.decorators import counselor_required

# Create your views here.
@counselor_required
def quiz_question_list(request):
    questions = QuizQuestion.objects.all()        #get all the questions from database
    return render(request, 'quiz_question_list.html', {'questions': questions})

@counselor_required
def quiz_question_create(request):
    if request.method == 'POST':
        counselor=request.user.counselor
        question_text = request.POST['question_text']
        question = QuizQuestion.objects.create(counselor=counselor, question_text=question_text)
        option_texts = request.POST.getlist('option_text')
        scores = request.POST.getlist('score')
        for i in range(len(option_texts)):
            option_text = option_texts[i]         #array handling data
            score = scores[i]
            QuizOption.objects.create(question=question, option_text=option_text, score=score)   #create optons
        return redirect('CounselorQuiz:quiz_question_list')
    return render(request, 'quiz_question_create.html')

@counselor_required
def quiz_question_update(request, question_id):
    question = get_object_or_404(QuizQuestion, id=question_id)    #404 if question not found
    options = question.quizoption_set.all()
    if request.method == 'POST':
        question_text = request.POST['question_text']
        question.question_text = question_text
        question.save()                                         #updating the question
        option_ids = request.POST.getlist('option_id')
        option_texts = request.POST.getlist('option_text')
        scores = request.POST.getlist('score')

        for i in range(len(option_ids)):
            option_id = option_ids[i]
            option_text = option_texts[i]            #array handling data for options
            score = scores[i]
            option = get_object_or_404(QuizOption, id=option_id)
            option.option_text = option_text                    #Update the option text and score in the QuizOption instance
            option.score = score
            option.save()

        return redirect('CounselorQuiz:quiz_question_list')
    return render(request, 'quiz_question_update.html', {'question': question, 'options': options})

@counselor_required
def quiz_question_delete(request, question_id):
    question = get_object_or_404(QuizQuestion, id=question_id)   #get the id of question to be deleted or 404 if not found
    if request.method == 'POST':
        question.delete()         #delete the question
        return redirect('CounselorQuiz:quiz_question_list')
    return render(request, 'quiz_question_delete.html', {'question': question})

CounselorQuiz/templates/quiz_question_create.html
{% extends 'counselornav.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'counselorschedulestyle.css' %}">
<body>
    <div class="moving_title">
        <span>A</span>
        <span>D</span>
        <span>D</span>
        <span></span>
        <span>A</span>
        <span></span>
        <span>Q</span>
        <span>U</span>
        <span>E</span>
        <span>S</span>
        <span>T</span>
        <span>I</span>
        <span>O</span>
        <span>N</span>
    </div>
    <br><br>
    <div class="container1">
        <!-- to create a new question -->
        <form method="post">
            {% csrf_token %}
            <label for="question_text">Question Text:</label>
            <input type="text" name="question_text" required><br><br>
            <label for="option_text">Option Text:</label>
            <input type="text" name="option_text" required><br><br>
            <label for="score">Score:</label>
            <input type="number" name="score" min="0" max="5" required><br><br>
            <label for="option_text">Option Text:</label>
            <input type="text" name="option_text" required><br><br>
            <label for="score">Score:</label>
            <input type="number" name="score" min="0" max="5" required><br><br>
            <label for="option_text">Option Text:</label>
            <input type="text" name="option_text" required><br><br>
            <label for="score">Score:</label>
            <input type="number" name="score" min="0" max="5" required><br><br>
            <input type="submit" value="Create" id="new">
        </form>
    </div>
</body>
{% endblock content %}

CounselorQuiz/templates/quiz_question_delete.html
{% extends 'counselornav.html' %}
{% block content %}
<!-- confirmation to delete question -->
    <h1>Delete Quiz Question</h1>
    <p>Are you sure you want to delete the following question?</p>
    <h3>{{ question.question_text }}</h3>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
{% endblock content %}

CounselorQuiz/templates/quiz_question_list.html
{% extends 'counselornav.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mental Health Quiz</title>
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'quiz_style.css' %}">
<body>
    <!-- viewing questions -->
    <h1 id="title">Mental Health Quiz</h1>
    <br><br>
    {% for question in questions %}
        <div class="question-container">
            <h3 class="question-text">{{ question.question_text }}</h3>
            <ul class="option-list">
                {% for option in question.quizoption_set.all %}
                    <li class="option-item">{{ option.option_text }} ({{ option.score }})</li>
                {% endfor %}
            </ul>
            <br>
            <a href="{% url 'CounselorQuiz:quiz_question_update' question.id %}"><button id="up"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a>
            <a href="{% url 'CounselorQuiz:quiz_question_delete' question.id %}"><button id="del"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a>
        </div>
    {% endfor %}
    <a href="{% url 'CounselorQuiz:quiz_question_create' %}"><button id="add">Add Question</button></a>
</body>
</html>
{% endblock content %}

CounselorQuiz/templates/quiz_question_update.html
{% extends 'counselornav.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'counselorschedulestyle.css' %}">
<body>
    <div class="moving_title">
        <span>E</span>
        <span>D</span>
        <span>I</span>
        <span>T</span>
        <span></span>
        <span>A</span>
        <span></span>
        <span>Q</span>
        <span>U</span>
        <span>E</span>
        <span>S</span>
        <span>T</span>
        <span>I</span>
        <span>O</span>
        <span>N</span>
    </div>
    <br><br>
    <div class="container1">
        <!-- form to update a question -->
        <form method="post">
            {% csrf_token %}
            <label for="question_text">Question Text:</label>
            <input type="text" name="question_text" value="{{ question.question_text }}" required><br><br>
            {% for option in options %}
                <input type="hidden" name="option_id" value="{{ option.id }}">
                <label for="option_text">Option Text:</label>
                <input type="text" name="option_text" value="{{ option.option_text }}" required><br><br>
                <label for="score">Score:</label>
                <input type="number" name="score" min="0" max="5" value="{{ option.score }}" required><br><br>
            {% endfor %}
            <input type="submit" value="Update" id="new">
        </form>
    </div>
</body>
{% endblock content %}